spring:
  application:
    name: api
  main:
    banner-mode: off
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy}
            scope: [ "openid","profile","email" ]
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

# CODEF 설정 (환경 변수가 있을 때만 활성화)
codef:
  enabled: ${CODEF_ENABLED:false}