spring:
  application:
    name: api
  main:
    banner-mode: off
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false


server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include: health,info
