name: build
on: [pull_request, push]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Wrapper가 정상인지 먼저 검증(보안/안정성)
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      # Linux에서 실행권한 보장(윈도우에서 커밋해도 안전)
      - name: Make gradlew executable
        run: chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: gradle/actions/setup-gradle@v3

      - name: Build API
        run: ./gradlew clean test :apps:api:build --no-daemon
